/**
 * Long-form copy for services that are ours rather than the dentistry site's.
 *
 * It uses the same shape as `dentalContent.ts` because it is rendered by the
 * same code — `renderDentalPage` builds the hero, the alternating bands, the
 * accordion and the closing call, and there is no reason for a medical page to
 * be built a second way. What differs is provenance: dentalContent.ts is
 * generated by an importer and must not be hand-edited, and this file is
 * written by hand and has no generator behind it.
 *
 * The section order is the one the practice asked for and the one a parent
 * actually reads in: what it is, who they will see, why it matters, when to
 * come, how the visit goes, where to go. Every heading is the question itself,
 * and every section opens by repeating it, so a reader skimming headings and a
 * reader landing mid-page from search both get an answer rather than a
 * continuation.
 */

import type { DentalPage } from "./dentalContent.ts";

export const serviceContent: Record<string, DentalPage> = {
  "/medical-care/well-child/": {
    description:
      "Well child checkups at Wasatch Pediatrics: what happens at a visit, who you will see, the recommended schedule from newborn to 21, and how to book at eight offices along the Wasatch Front.",
    eyebrow: "Medical Care",
    lead: "A well-child visit is the appointment we make time for when nothing is wrong, so that we know your child before anything is.",
    hero: "/wp-content/uploads/2022/05/WAS21-0020_Website_Header_New-Patients_Mobile_1000x400_v1-1.jpg",
    promises: [
      {
        icon: "user-focus",
        title: "The same faces",
        text: "We book you with your own pediatrician wherever we can, because a doctor who remembers last year catches what a stranger cannot.",
      },
      {
        icon: "calendar",
        title: "Booked a year ahead",
        text: "We schedule the next checkup before you leave, so the visit that is easy to postpone is already on the calendar.",
      },
      {
        icon: "map-pin",
        title: "Eight offices",
        text: "We see children for checkups at every one of our locations, from Farmington to Draper to Park City.",
      },
    ],
    sections: [
      {
        heading: "What is a well-child visit?",
        body: [
          "A well-child visit is an appointment we schedule while your child is healthy. Nobody is sick and nothing hurts, and that is the point: it is the one visit built around looking at your whole child rather than at a single complaint.",
          "In about half an hour we check growth against your child's own history, examine them from head to toe, and test vision and hearing. We complete developmental screening in the early years and mental health screening in the later ones, bring immunizations up to date, and answer whatever you have been wondering about since the last visit. We can also sign school, sports, camp, and mission forms while you are in the room.",
          "Usually nothing dramatic happens, and that is a good outcome. Most of what we do is confirm that your child is on their own track. The value is in having a record of that track, so that the year something moves off it, we notice quickly.",
        ],
      },
      {
        heading: "Who will my child see?",
        body: [
          "Your child will see a pediatrician or advanced practice provider, and we keep it the same person visit after visit wherever the schedule allows. A provider who examined your child at two months remembers things no chart summarises, and that memory is what turns a borderline measurement into either reassurance or a plan.",
          "That provider leads the team. If your child needs a dietitian, a lactation consultant, a therapist, a psychologist for testing, or a specialist outside the practice, we make the connection during the visit and stay involved afterwards rather than handing you a phone number.",
          "You are on that team too, and you have information none of us do. What you have noticed at home between visits is usually the most useful thing said in the room.",
        ],
      },
      {
        heading: "Why do these visits matter when my child is well?",
        body: [
          "They matter because your child is well. Almost everything we screen for arrives quietly and is easiest to treat before anyone at home has a reason to worry: a growth curve that has flattened, hearing loss behind delayed speech, curvature of the spine, high blood pressure, anaemia, anxiety, or a developmental difference.",
          "These visits are also how vaccines actually happen. The immunization schedule is built around well-child ages, so a family who keeps their appointments stays protected without ever thinking about it. A family who skips a year usually finds out at a school deadline.",
          "And they build the relationship. A teenager will tell a doctor they have known since kindergarten things they will not tell a stranger in an urgent care room. Fourteen years of ordinary visits is what buys that conversation.",
        ],
      },
      {
        heading: "When should my child come in?",
        body: [
          "Come in on the schedule below, which follows the American Academy of Pediatrics recommendations. Visits are frequent in the first two years, because that is when growth and development move fastest, and then settle into once a year.",
          "We also handle school, sports, camp, and mission physicals at these visits. If your child needs a form signed this year, book the annual well-child visit rather than a separate physical and you will get both.",
        ],
        steps: [
          { title: "Newborn", text: "Within days of coming home, and again at two weeks." },
          { title: "First year", text: "At 1, 2, 4, 6, and 9 months, then the first-birthday visit at 12 months." },
          { title: "Toddler", text: "At 15, 18, 24, and 30 months, as walking, talking, and eating all change." },
          { title: "Age 3 to 21", text: "Once a year, every year, including the teenage visits." },
        ],
      },
      {
        heading: "How does a visit go?",
        body: [
          "You will be in and out in around half an hour, and it goes the same way every time. Our staff weighs and measures your child and takes their vitals. Your provider then works through the exam, the screenings due at that age, and the questions you brought. We give vaccines last, so that nothing frightening happens before the part where your child has to hold still.",
          "Bring anything that helps us: your child's immunization record if you are new to us, forms that need signing, and a written list of the things you meant to ask. Almost every parent forgets one, and a written list is the only reliable fix.",
          "Before you leave, we book the next visit. It takes twenty seconds at the front desk and it is the single thing that most reliably keeps a family on schedule.",
        ],
      },
      {
        heading: "Where can we go?",
        body: [
          "Come to any of our eight offices — Murray, Salt Lake, Willow Creek, Draper, West Jordan, Bountiful, Farmington, and Park City. Most families pick the one that is easiest on a weekday morning rather than the one nearest their house.",
          "If you are deciding between two, the pages below work through it city by city: which offices are closest, roughly how long the drive takes, and what to weigh when the nearest office and the most convenient office are not the same one.",
        ],
      },
    ],
    reassurance:
      "If it has been three years since the last visit, book anyway. We are far more interested in catching up with your child than in counting the visits you missed.",
    faqs: [
      {
        q: "How long does a well-child visit take?",
        a: "Plan on about 30 minutes. Newborn visits and teenage visits often run a little longer, because there is more to talk through.",
      },
      {
        q: "Does a checkup count as preventive care on my insurance?",
        a: "Most plans cover well-child visits as preventive care, often with no copay. Vaccines given at the visit are usually covered the same way. Anything we treat as a separate problem during the visit may be billed separately, and we will tell you in the room if that is happening.",
      },
      {
        q: "Can I get a school or sports physical at the same visit?",
        a: "Yes. We complete school, sports, camp, and mission forms as part of the annual visit. Bring the paperwork and we will fill it in while you are here.",
      },
      {
        q: "What if my child is due for a visit but has a cold?",
        a: "Call us. A mild cold usually does not stop a well-child visit, but if your child is genuinely unwell we would rather see them as a sick visit and do the full check once they are better.",
      },
      {
        q: "My child is behind on vaccines. Is it too late?",
        a: "No. There is a catch-up schedule for every vaccine and we will build one at the visit. Being behind is common, and it is fixable.",
      },
      {
        q: "Do you see teenagers?",
        a: "We see children through age 21. The teenage visits cover mental health, sport, and sleep, and include time alone with the provider if your teenager wants it.",
      },
    ],
  },
};
